### ISSUE TITLE
migrate debian:buster -> debian:Bullseye (released 14 August 2021) 

### ISSUE THREAD

**Issue by alek-w** [adoptium/containers#124]
https://www.debian.org/News/2021/20210814

**Comment by gdams** [comment]
@alek-w we currently provide an Ubuntu base docker image, not a Debian one so I'm not sure this is relevant to the project

**Comment by alek-w** [comment]
@gdams Could ypu tell pls
who is responsible for debain containers [there](https://hub.docker.com/r/adoptopenjdk/openjdk11) ?

[this guys ](https://github.com/AdoptOpenJDK/openjdk-docker/issues/614) says that they are not
