### ISSUE TITLE
Explicitly install packages in alpine so that "apk del apk-tools" does not break the JVM

### ISSUE THREAD

**Issue by DRoppelt** [adoptium/containers#136]
Hi guys,

I very much appreciate the effort towards the native musl integration with the JVM and alpine.

In our setup, we do so custom hardening of images (i.e. rootless) and as part of it, we drop "apk-tools" to remove the ability to add any package and possibly alter a running service in a production environment.

We noticed that the musl-native images appear to have a dependency that is dropped when apk-tools is removed. Sounds a lot like there is an implicit dependency that is removed. 

```
$ java -version
#6 0.554 Error loading shared library libz.so.1: No such file or directory (needed by /opt/java/openjdk/bin/../lib/jli/libjli.so)
#6 0.554 Error relocating /opt/java/openjdk/bin/../lib/jli/libjli.so: inflate: symbol not found
#6 0.554 Error relocating /opt/java/openjdk/bin/../lib/jli/libjli.so: inflateEnd: symbol not found
#6 0.554 Error relocating /opt/java/openjdk/bin/../lib/jli/libjli.so: inflateInit2_: symbol not found
```

With some tinkering & looking at `apk info --depends apk-tools` I found that following 2 libs seem to do the trick

```
/ # apk del apk-tools -s
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.14/main: No such file or directory
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.14/community: No such file or directory
(1/7) Purging ssl_client (1.33.1-r6)
(2/7) Purging apk-tools (2.12.7-r0)
(3/7) Purging libretls (3.3.3p1-r2)
(4/7) Purging ca-certificates-bundle (20191127-r5)
(5/7) Purging libssl1.1 (1.1.1l-r0)
(6/7) Purging libcrypto1.1 (1.1.1l-r0)
(7/7) Purging zlib (1.2.11-r3)
OK: 9 MiB in 17 packages
/ # apk add zlib libretls
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
OK: 9 MiB in 17 packages
/ # apk del apk-tools -s
(1/1) Purging apk-tools (2.12.7-r0)
OK: 9 MiB in 17 packages
/ #
```
-> with `apk add libretls zlib`, no dependencies are uninstalled.

And  `java -version` (and likely any other startup of the JVM) works again

I believe these packages should be explicitly installed as they are required for the jvm.

Any thoughts on this`?

Here 2 Dockerfiles to reproduce the issue:

```
FROM eclipse-temurin:11.0.13_8-jre-alpine

RUN apk info --depends apk-tools
RUN apk del apk-tools
# Breaking
RUN java -version
```

```
FROM eclipse-temurin:11.0.13_8-jre-alpine

RUN apk info --depends apk-tools
RUN apk add libretls zlib
RUN apk del apk-tools
# Fixed
RUN java -version
```

It looks like just "zlib" would be enough, but I added "libretls" as it results in not a single deletion of a package, just apk-tools itself.
Not sure what either of them do in context of apk-tools and why zlib seems to be necessary for the JVM

**Comment by DRoppelt** [comment]
Oh I just noticed the label "help wanted" on it.

I will work on a PR then

**Comment by gdams** [comment]
@DRoppelt I've created a PR (https://github.com/adoptium/containers/pull/217) please can you confirm that this is the required code change?
