### ISSUE TITLE
Deprecate Microsoft ltsc2016 images

### ISSUE THREAD

**Issue by gdams** [adoptium/containers#139]
The upstream image has now been deprecated the the docker hub folks won't accept anymore pull requests with these files inside. I suggest we remove the dockerfiles here.

**Comment by karianna** [comment]
Agreed, I don't think MSFT is pushing this technology in the long term.

**Comment by karianna** [comment]
Should raise this at next PMC meeting actually now that I think about it.

**Comment by gdams** [comment]
> Should raise this at next PMC meeting actually now that I think about it.

We can certainly discuss but we don't have a choice with this one as the Dockerhub folks won't allow us to push updates without the ltsc2016 images gone. See https://github.com/docker-library/official-images/pull/11661 for context

**Comment by karianna** [comment]
Ah OK, I've informed hte PMC in that case - let's land this as it'll block the release otherwise
