### ISSUE TITLE
jdk-11.0.14.1+1 not available for 11-alpine yet

### ISSUE THREAD

**Issue by DRoppelt** [adoptium/containers#163]
When visiting adoptium.net, I am greeted with a

> 11th February 2022: If you have recently picked up the jdk-11.0.14+9 release, please update to jdk-11.0.14.1+1 to pick up a fix for a regression in the HTTPClient code. 

But I cannot find an jdk-11-alpine container with 11.0.14.1, only the 11.0.14 (when mentioned explicitly tagger) or "11-jdk-alpine"  that have a "last updated 22 days ago" (== before 11th February)

I am not familiar with the update process in this repo, I can try to submit a PR, but would gladly leave it up to someone who could get it out the door fast. I am not familiar with the severity of the regression.

If it is not urgent, I would like to help with a PR?

**Comment by karianna** [comment]
@gdams - our pipelines should have auto-triggered these no?

**Comment by gdams** [comment]
@karianna we haven't released that patch for alpine yet
