### ISSUE TITLE
alpine images can't run RocksDBJNI

### ISSUE THREAD

**Issue by stijnopheide** [adoptium/containers#170]
When running a project that has [rocksdbjni](https://search.maven.org/artifact/org.rocksdb/rocksdbjni) on the classpath, the JVM will encounter the following error:

```
/tmp/librocksdbjni7856201673520504504.so: Error loading shared library libstdc++.so.6: No such file or directory (needed by /tmp/librocksdbjni7856201673520504504.so)
```

Image used: `eclipse-temurin:8-alpine`

This is due to libstdc++ not being installed. The problem can be resolved with

```
apk add --no-cache libstdc++
```

I'm not sure if this is a goal of the project to support, so feel free to close if it isn't.

**Comment by karianna** [comment]
Indeed, we're deliberately not adding libstdc++ for Alpine containers :-)
