### ISSUE TITLE
18-jre-alpine seems to be missing

### ISSUE THREAD

**Issue by madisparn** [adoptium/containers#180]
Would be nice to be able to upgrade from 17-jre-alpine to 18-jre-alpine.
Ala https://github.com/adoptium/containers/commit/3bb1ab86003a3f45f0d430ea5737089dd83ac0f9

**Comment by karianna** [comment]
Should arrive in 18.0.1 in the coming weeks.

**Comment by gdams** [comment]
@madisparn it will be available once https://github.com/docker-library/official-images/pull/12359 lands
