### ISSUE TITLE
Removal of architectures other than amd64

### ISSUE THREAD

**Issue by nroduit** [adoptium/containers#185]
The latest automatic updates have removed all architectures except amd64, see https://github.com/adoptium/containers/commit/1c2bc74272de764359d9840d73a6caa2d423b438

I guess it's not intentional.

**Comment by gdams** [comment]
It's just the way the GitHub bot updates the files. We create a new one when a new release is available and then automatically add each architecture back when it's been made available. Do you rely in some way on the dockerfiles themselves?

**Comment by nroduit** [comment]
Thanks for the feedback. Not directly, it's just that I couldn't find the 18.0.1 image on docker hub.
