### ISSUE TITLE
eclipse-temurin:17-jdk Java fails to start

### ISSUE THREAD

**Issue by nikortel** [adoptium/containers#214]
Eclipse Temurin 17 

How to reproduce:
`docker run --rm eclipse-temurin:17-jdk java -version`

Result:
```
[0.004s][warning][os,thread] Failed to start thread - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# //hs_err_pid1.log
```

**Comment by karianna** [comment]
In the linked bug report it seems to be using 17.0.2 when it should be using 17.0.3 - also what size memory are you running that container as?

**Comment by nikortel** [comment]
MEM USAGE / LIMIT     MEM %
1.598MiB / 15.63GiB   0.01%

Linked Gradle report the 7.0.2 just shows that earlier version is working

**Comment by karianna** [comment]
Can you try `docker run --rm eclipse-temurin:17-jdk java --version` (note the extra `-` character for the java --version bit)

**Comment by nikortel** [comment]
`docker run --rm eclipse-temurin:17-jdk java --version`
```
[0.002s][warning][os,thread] Failed to start thread - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# //hs_err_pid1.log
```

**Comment by karianna** [comment]
Hmm, I get:

```
 docker run --rm eclipse-temurin:17-jdk java --version
openjdk 17.0.3 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)
```

OK, what host O/S and Docker version are you running?

**Comment by nikortel** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:21 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:32 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  
The 17.0.2_8-jdk works with the same setup
```
docker run --rm eclipse-temurin:17.0.2_8-jdk java --version
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)
  ```

**Comment by karianna** [comment]
I've asked in our Slack community for other Ubuntu users to try and repro

**Comment by nikortel** [comment]
Seems to work with newer docker:
Client: Docker Engine - Community
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:17:23 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:15:28 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```
docker run --rm eclipse-temurin:17-jdk java --version
openjdk 17.0.3 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)
```

**Comment by nikortel** [comment]
Do we need to investigate this further or are we satisfied that this version does not work with older Docker versions? For me the docker update resolved the issue.

**Comment by karianna** [comment]
I think we can close it out - thanks for checking!

**Comment by karianna** [comment]
https://github.com/adoptium/containers/issues/215#issuecomment-1142046045

**Comment by epugh** [comment]
I experienced the same thing with "Docker 19.03.12 on Ubuntu 20.04" that is available from DigitalOcean.   I'm going to try and update my Docker!
