### ISSUE TITLE
Public Key not found error with eclipse-temurin:11 image updated on 27th May 2022

### ISSUE THREAD

**Issue by shivpatel1** [adoptium/containers#216]
We are using eclipse-temurin:11 [using ubuntu 20.04] as a base image since a long time.
Yesterday, we pulled the same image from Dockerhub and started noticing below errors while building our internal images.
We have "apt-get update .... " command in our Dockerfile which results into these errors.

    Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
    Get:2 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
    Err:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
      The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C
    Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [109 kB]
    Err:2 http://archive.ubuntu.com/ubuntu jammy InRelease
      The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 871920D1991BC93C

Seems like this is happening after eclipse-temurin started using ubuntu 22.04 .

As per few responses to other questions on ubuntu forum, I added below lines in my Dockerfile just before "apt-get update.." command..

apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 871920D1991BC93C

This was giving below error :

[91mE: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
[0mThe command '/bin/sh -c apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 871920D1991BC93C' returned a non-zero code: 255

So, we thought gnupg needs to be installed but that again needs apt-get update / install commands which fails with same PUBLIC KEY not found error.

Is this a known behavior in latest eclipse-temurin:11 ? Is there any solution available ?

Below is the partial content of our Dockerfile.

FROM xxxxxx/eclipse-temurin:11

ENV TOMCAT_MAJOR 9
ENV TOMCAT_VERSION 9.0.62
...
...
RUN apt-get update -y && \
    curl -jksSL -o xxxxx
...
...

**Comment by shivpatel1** [comment]
@gdams  : Thank you for checking this.

docker run -it eclipse-temurin:11 apt-get update 
This command runs in my environment as well. 

We have our application specific Dockerfile which contains eclipse-temurin:11 as a base image. And our Dockerfile contains apt-get update command. While using this Dockerfile to create an image of our application, it fails with the PUBLIC KEY error while executing apt-get update command it has.

If I use old image of eclipse-temurin [8 months old - which I have locally] as a base image then it works. The issue comes if I use this new one [May 27 2022 update].

**Comment by gdams** [comment]
This one is obviously hard to diagnose without seeing your Dockerfile, If I understand correctly you're saying that the difference is that the `apt-get update` command is run as a step in your Dockerfile?

See this sample Dockerfile (which I think mirrors your setup):

```dockerfile
FROM eclipse-temurin:11
RUN apt-get update 
```

If I build that it works on my end:

```bash
docker build -f Dockerfile .
[+] Building 1.6s (6/6) FINISHED                                                                                                                     
 => [internal] load build definition from Dockerfile                                                                                            0.0s
 => => transferring dockerfile: 87B                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                               0.0s
 => => transferring context: 2B                                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/eclipse-temurin:11                                                                           0.0s
 => [1/2] FROM docker.io/library/eclipse-temurin:11                                                                                             0.0s
 => [2/2] RUN apt-get update                                                                                                                    1.5s
 => exporting to image                                                                                                                          0.1s
 => => exporting layers                                                                                                                         0.1s
 => => writing image sha256:a76e1c5219653830fa33ab343a1f37be7e6d08d4d4efb7dc20d8dcaf9682529f                                                    0.0s 
                                                                                                                                                     
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them   
```

**Comment by shivpatel1** [comment]
@gdams  :  Yes, I tried this today and it seems to be working. The same Dockerfile was not working for two days continuously and I opened this issue here. But today, somehow I am not getting that PUBLIC KEY related errors from ubuntu. 

Thank you for your time. I will come back if I will start seeing the same issue again. Closing this case from my end.

**Comment by shivpatel1** [comment]
@gdams  :  We were facing this issue on environments where we had Docker 18.x.x.  The environments where we had Docker 19.x.x  or Docker 20.x.x were noticed to work well.

**Comment by tholu** [comment]
Running into the same issue with Docker version 19.03.15, build 99e3ed8919 right now.

**Comment by shivpatel1** [comment]
@tholu  : I am not sure what is causing it at your end. Because the same is working for me. Below is the snippet just taken in one of my machine.

![image](https://user-images.githubusercontent.com/12895460/189313266-dfe044ce-b60f-468e-a45c-a81328637bcc.png)

**Comment by tholu** [comment]
@shivpatel1 That is so weird, since I run the exactly same version:

```
# docker -v
Docker version 19.03.15, build 99e3ed8919
```

So much about reproducibility 😅
