### ISSUE TITLE
Problem with Eclipse Temurin 17-JDK image on Docker Hub

### ISSUE THREAD

**Issue by entrusc** [adoptium/containers#219]
Seems that there is a bug in the image that was pushed roughly 2 hours ago with the tag 17-JDK to docker hub:

![grafik](https://user-images.githubusercontent.com/2729000/172347689-8c08b996-678a-4145-9353-761a981d1b05.png)

The linux amd64 version jdk will not start and complain with an out of memory exception like this even though we have over 50GB of memory left. Also I've tested it with an older tag and it works just fine:

```
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# /tmp/hs_err_pid7.log
[0.003s][warning][os,thread] Failed to start thread - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
```

Not 100% sure if this is the correct repo to report the issue, if not, please just close the issue. Thanks!

**Comment by jerboaa** [comment]
Looks like a dupe of #214 and #215. Please check your docker version.

**Comment by entrusc** [comment]
Thanks @jerboaa - after upgrading to Docker version 20.10.17 the problem disappeared. Closing the ticket.
