### ISSUE TITLE
Missing Alpine images in the Docker registry

### ISSUE THREAD

**Issue by domenjesenovec** [adoptium/containers#226]
Under [222](https://github.com/adoptium/containers/pull/222) we have upgraded to latest Alpine version (3.16), but in [Docker Hub](https://hub.docker.com/_/eclipse-temurin?tab=tags) there are still no new Alpine based images. For example pulling eclipse-temurin:17-alpine will pull an image still based on Alpine 3.15 (3.15.4).

What needs to happen for new images to appear in the Docker Hub?

**Comment by karianna** [comment]
@gdams - This should be updated at DockerHub now no?

**Comment by gdams** [comment]
We're waiting for https://github.com/docker-library/official-images/pull/12655 to be merged
