### ISSUE TITLE
[Bug]: Docker images were re-built and existing tags were overridden

### ISSUE THREAD

**Issue by andersonkyle** [adoptium/containers#255]
### Please add the exact image (with tag) that you are using

eclipse-temurin:17.0.4_8-jre

### Please add the version of Docker you are running

20.10.14

### What happened?

A number of my applications are using `eclipse-temurin:17.0.4_8-jre` as their base image.  Our Dockerfile uses `curl` which was provided by the temurin base image up until [recently](https://github.com/adoptium/containers/pull/242).  The issue is that the `17.0.4_8-*` images were re-built and pushed to Docker Hub overriding what was there previously.

For less specific tags like `latest` or `17` perhaps that's fine but for a tag as specific as `17.0.4_8-jre` I wouldn't expect the image to change once released, especially in a backwards incompatible manner (e.g. changing dependencies).

This might be related to https://github.com/adoptium/containers/issues/68

### Relevant log output

```shell
/bin/sh: 1: curl: not found
```

**Comment by zdtsw** [comment]
I think the intention was to just re-build jdk8 from 8u342-b07 to 8u345-b01 with the changes (from curl to wget) in https://github.com/adoptium/containers/pull/242

The re-build of other images, i.e 17.0.4_8-* was a mistaken done in https://github.com/docker-library/official-images/commit/955f86a0b690a677c7077b3364b1c8c3a76678da . 

Either these non-jdk8 images should have new tags or in the original commit to add wget but keep curl till next release

**Comment by cec** [comment]
Is it possible to rebuild the overwritten tags to restore the previous state?

**Comment by gdams** [comment]
Hi all,

So there's two parts to this issue. The rebuilding of existing tags is pretty common in the docker world, it's mostly done when security updates in the base image are published.

The recent dependency change to remove curl and swap with wget does seem more inconvenient and would be considered a breaking change.

The simplest option here would be to re-add curl as a dependency and publish the images again
