### ISSUE TITLE
Docker tag ubi-jre not working

### ISSUE THREAD

**Issue by Ariana-Hlavaty-i2** [adoptium/containers#258]
**What are you trying to do?**
docker pull adoptopenjdk/openjdk11:ubi-jre

**Expected behaviour:**
Image pulled from DockerHub

**Observed behaviour:**
ubi-jre: Pulling from adoptopenjdk/openjdk11
no matching manifest for linux/amd64 in the manifest list entries

**Any other comments:**
Seems to have been broken today 15th August 2022

**Comment by sxa** [comment]
(Bear in mind we do not offer much in the way of support for these images now, as we've moved only supporting a subset of the distributions in our [official docker images for Temurin](https://hub.docker.com/_/eclipse-temurin)) although the automation is still in place to keep them updated.

**Comment by Ariana-Hlavaty-i2** [comment]
The tag is now working. Closing
