### ISSUE TITLE
Support for ubi / ubi-minimal

### ISSUE THREAD

**Issue by soufianebenali** [adoptium/containers#259]
Hi Guys,

There is any plan in the future to support ubi?

Can we collaborate (me and my colleagues) to extend the jdk docker images to support also ubi?

Thanks
Soufiane

**Comment by karianna** [comment]
At this stage we are only offering support for the DockerHub official images: https://hub.docker.com/_/eclipse-temurin

**Comment by soufianebenali** [comment]
any plan to extend this in the next stages?

We can also open new PR to collaborate in this.

**Comment by karianna** [comment]
Hi @soufianebenali - We discussed this at the PMC and we need to stick to the DockerHub officially supported images.  Red Hat may decide to have UBI accepted as an official image in which case we'd be able to add it as a default.

**Comment by gdams** [comment]
@soufianebenali for more context please follow https://github.com/docker-library/official-images/issues/9445 which is the thread where the official maintainers are discussing whether to support ubi or not. Once they've confirmed that they are happy for official images to be based of Ubi it becomes a much easier discussion for us. In the meantime you could use a multi-stage dockefile to have an ubi base:

```dockerfile
FROM redhat/ubi8

ENV JAVA_HOME=/opt/java/openjdk
COPY --from=eclipse-temurin:17 $JAVA_HOME $JAVA_HOME
ENV PATH="${JAVA_HOME}/bin:${PATH}"

# Install base dependencies
RUN dnf install -y tzdata openssl curl wget ca-certificates fontconfig gzip tar \
    && dnf clean all \
    && echo javac --version && javac --version \
    && echo java --version && java --version

CMD ["she'll"]
```
