### ISSUE TITLE
[Bug]: Frequent java OOM problems requiring JDK11.0.16.1 release

### ISSUE THREAD

**Issue by jennyowen** [adoptium/containers#264]
### Please add the exact image (with tag) that you are using

eclipse-temurin:11.0.16_8-jdk

### Please add the version of Docker you are running

Docker version 20.10.17, build 100c701

### What happened?

Hi,
At Neo4j we're finding that we are getting persistent, repeatable OOM failures because of [this OpenJDK java bug](https://bugs.openjdk.org/browse/JDK-8292260) which has already been fixed in openjdk `11.0.16.1`.

I can see from the container source that you already have development images with this java version already: 
https://github.com/adoptium/containers/blob/2ddd4deef78a4b58e05518423c4f51718ef79647/11/jdk/ubuntu/jammy/Dockerfile.releases.full#L34

My question is, **when will the `11.0.16.1` image be released to dockerhub?** 

cc @glindroth @MishaDemianenko @parnmatt

### Relevant log output

```shell
N/A
```

**Comment by karianna** [comment]
Likely this week when the testing is complete.

**Comment by jennyowen** [comment]
ok  great, thank you!
