### ISSUE TITLE
[Bug]: build of new image 17.0.5...

### ISSUE THREAD

**Issue by mcarbonneaux** [adoptium/containers#312]
### Please add the exact image (with tag) that you are using

the new eclipse-temurin:17.0.5 !

### Please add the version of Docker you are running

na

### What happened?

the repository https://github.com/adoptium/containers has been updated for 17.0.5+8, but jenkins host https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/eclipse-temurin/ not see the news version.... 
and no news version on docker hub : https://hub.docker.com/_/eclipse-temurin/tags?page=1&name=17 ... 

is normal ?

**Comment by karianna** [comment]
@mcarbonneaux DockerHub can take a few days before accepting our new images.

**Comment by gdams** [comment]
@mcarbonneaux they've available now. Sorry for not updating this issue sooner
