### ISSUE TITLE
libawt_xawt.so

### ISSUE THREAD

**Issue by gastendonk** [adoptium/containers#331]
### Please add the exact image (with tag) that you are using

eclipse-temurin:17.0.5_8-jdk-alpine

### Please add the version of Docker you are running

Docker version 20.10.18, build b40c2f6

### What happened?

Xvfb :1 -screen 0 1920x1080x24 &
export DISPLAY=":1"
./gradlew -Djava.awt.headless=true ....

How can I fix this error?

java.lang.UnsatisfiedLinkError: Can't load library: /opt/java/openjdk/lib/libawt_xawt.so

I use Image jenkins/agent:3085.vc4c6977c075a-2-alpine-jdk17 which uses eclipse-temurin:17.0.5_8-jdk-alpine.

**Comment by gastendonk** [comment]
It works with jenkins/agent:3085.vc4c6977c075a-2-jdk17 = bullseye.

**Comment by karianna** [comment]
@gdams to confirm but I'm pretty sure we only produce headless Alpine builds.

**Comment by gdams** [comment]
Yeah, the builds we produce are headless only. If you require a headful build I would suggest you switch to the ubuntu images unless you explicitly require alpine
