### ISSUE TITLE
[Bug]: Add maven toolchain generation

### ISSUE THREAD

**Issue by jgsuess** [adoptium/containers#335]
### Please add the exact image (with tag) that you are using

eclipse-temurin:17:djk

### Please add the version of Docker you are running

23:0:0

### What happened?

For builds that want to  configure via [maven toolchain](https://maven.apache.org/plugins/maven-toolchains-plugin/toolchains/jdk.html), it would be nice to have a default configuration available. Could you include that with the image, please?

**Comment by jgsuess** [comment]
https://github.com/AdoptOpenJDK/openjdk-docker-build-tools/issues/15

**Comment by karianna** [comment]
I'm afraid the PMC decided not to produce specialised Docker containers for Maven or Gradle etc to try to keep the maintenance purely to JDK containers.
