### ISSUE TITLE
More recent windows base image?

### ISSUE THREAD

**Issue by timja** [adoptium/containers#35]
The windows images appear to be ltsc2016 and 1809

Could ltsc2019 and ltsc2022 be offered instead? (they are the featured tags on https://hub.docker.com/_/microsoft-windows-servercore)

Windows is a bit different to linux in that you need to run containers on the same OS version as the host.

**Comment by gdams** [comment]
Currently, we are restricted by what the official docker hub folks are able to build on.

To clarify, `1809` is just an alias for `ltsc2019`. See [base-image-lifecycle](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/base-image-lifecycle) (note the "OS build" column at that link where 2019 and 1809 have the same version).

**Comment by gdams** [comment]
Closing, for now, feel free to re-open if this didn't answer your question
