### ISSUE TITLE
No JVMCI compiler found on JVM 19

### ISSUE THREAD

**Issue by yanns** [adoptium/containers#360]
HI,
I'm using the docker image "eclipse-temurin:19.0.2_7-jre-focal" (I've also tried with "eclipse-temurin:19.0.2_7-jdk-focal").

When I try to use the Graal JIT Compiler by using the following options:
```
-XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler
```

I got the following error:
```
Cannot use JVMCI compiler: No JVMCI compiler found
```

Is it expected?

**Comment by karianna** [comment]
@yanns - It is, the Graal compiler was removed from OpenJDK (but it may make its way back in a future release)

**Comment by yanns** [comment]
Thanks for the quick answer. I was not aware of that decision.

**Comment by yanns** [comment]
Maybe related:
- https://openjdk.org/jeps/410
- https://bugs.openjdk.org/browse/JDK-8255616
