### ISSUE TITLE
[Bug]: All April 2023 "arm32" images are not being published to dockerhub

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/containers#384]
All arm32 Linux binaries have been published but the dockerhub images are not being updated.........?

https://hub.docker.com/r/arm32v7/eclipse-temurin/

**Comment by andrew-m-leonard** [comment]
Looks like we need to add arm32 back into: https://github.com/docker-library/official-images/blob/master/library/eclipse-temurin

**Comment by andrew-m-leonard** [comment]
Update: https://github.com/docker-library/official-images/pull/14573

**Comment by karianna** [comment]
> Update: [docker-library/official-images#14573](https://github.com/docker-library/official-images/pull/14573)

That's merged now, can we close this?

**Comment by andrew-m-leonard** [comment]
@gdams arm32 still not being publish, any ideas? https://hub.docker.com/r/arm32v7/eclipse-temurin/

**Comment by andrew-m-leonard** [comment]
They are published, eg: https://hub.docker.com/layers/library/eclipse-temurin/11.0.19_7-jdk-focal/images/sha256-6575ec4bac4327601868fec6b131927767ed07b59ad5d5cdc48c4a0316b7fc70?context=explore

They are just not visible when queried by architecture: https://hub.docker.com/r/arm32v7/eclipse-temurin/
