### ISSUE TITLE
jdk-20: Provide base image for Ubuntu Focal (20.04)

### ISSUE THREAD

**Issue by esiqveland** [adoptium/containers#386]
I noticed that jdk-19 has a built for Focal (20.04): https://github.com/adoptium/containers/tree/main/19/jdk/ubuntu/focal

Will there be a build for jdk-20 as well?

**Comment by tellison** [comment]
@esiqveland apologies for the delay in responding to your question. Thanks for the question. We talked about this topic in the PMC meeting.

The decision to remove Focal (20.04) was a deliberate choice. We are now producing Temurin images at a range of JDK versions [based upon Jammy (22.04)](https://hub.docker.com/_/eclipse-temurin/tags?page=1&name=jammy), however, from Temurin JDK20 we are preparing ourselves (and our users!) for the end of support of Focal, and dropping production of Focal-based images that will be long term supported as part of the Temurin JDK21 releases, expected in September 2023.

We show instructions in [the eclipse-temurin image description](https://hub.docker.com/_/eclipse-temurin) of how you can move our images to use a base image of your choice.
