### ISSUE TITLE
Temurin >17 does not support ppc64le

### ISSUE THREAD

**Issue by roy20021** [adoptium/containers#395]
Hello,

the latest support of platform ppc64le is image 17, after that despite there are the jdk available for later versions the docker images are not.

I see that they were built few months ago:
![image](https://github.com/adoptium/containers/assets/1174320/9f823fb6-ae81-496f-a798-0519cc9feb24)

Why are they not supported anymore? 
Can you push back also such images?

**Comment by karianna** [comment]
@roy20021 Unfortunately we were not able to complete testing for Java 20 for that platform.  We will be making sure that Java 21 is complete
