### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by sravula84** [adoptium/containers#399]
### Please add the exact image (with tag) that you are using

eclipsejdk8-alpine

### Please add the version of Docker you are running

Docker version 24.0.1, build 6802122

### What happened?

we are trying to install certs 

ADD https://xxxxxxx.packages/cacerts/p2pc1_root.pem /usr/local/share/ca-certificates/p2pc1_root.pem
ADD https://xxxxxxx.packages/packages/cacerts/p%20Intermediate.crt /usr/local/share/ca-certificates/rIntermediate.crt
RUN chmod 644 /usr/local/share/ca-certificates/p2pc1_root.pem
RUN chmod 644 /usr/local/share/ca-certificates/Intermediate.crt

getting  > Received fatal alert: handshake_failure , while using docker build .

looks like missing Ciphers in 8-jdk-alpine, could you please suggest ?

**Comment by karianna** [comment]
Can you post your full docker file?

**Comment by sravula84** [comment]
FROM eclipse-temurin:8-jdk-alpine
ENV  APP_HOME=/opt/pro/java

# Copying cacerts needed by the jvm when gradle runs and obtains dependencies from artifactory
COPY resources/cacerts /opt/java/openjdk/lib/security/

RUN apk add curl openssl
RUN apk add --update --no-cache ca-certificates
ADD https://artifactory.jfrog.com/artifactory/packages/cacerts/p2pc1_root.pem /usr/local/share/ca-certificates/p2pc1_root.pem
ADD https://artifactory.jfrog.com/artifactory/packages/cacerts/Pro%20Intermediate.crt /usr/local/share/ca-certificates/ProIntermediate.crt
RUN chmod 644 /usr/local/share/ca-certificates/p2pc1_root.pem
RUN chmod 644 /usr/local/share/ca-certificates/ProIntermediate.crt

RUN update-ca-certificates
RUN set -eux && \
    apk add --no-cache --no-progress dos2unix

**Comment by karianna** [comment]
I think you forgot to register a key - see https://adoptium.net/en-GB/installation/linux/#_alpine_linux_instructions
