### ISSUE TITLE
Provide documentation to allow users to produce their own images.

### ISSUE THREAD

**Issue by karianna** [adoptium/containers#4]
Something like:

If you prefer an OS base image distribution that we don't provide an image for, you can copy the JDK using the COPY --from instruction in a Dockerfile, similar to the following example:

*Dockerfile*

```
# Example of using Temurin image to create a new image with a different base image
FROM debian:buster-slim
ENV JAVA_HOME /usr/lib/jvm/temurin-11-amd64
ENV PATH "${JAVA_HOME}/bin:${PATH}"
COPY --from=dockerhub.com/eclipse-temurin/jdk:11-ubuntu $JAVA_HOME $JAVA_HOME

# Continue with your application deployment
RUN mkdir /opt/app
COPY japp.jar /opt/app
CMD ["java", "-jar", "/opt/app/japp.jar"]
To create a custom Java runtime image, use a Dockerfile similar to the following example:
```

**Comment by sxa** [comment]
@gdams Unless I misheard I believe you said in one of our calls today that you'd done this. Can you clarify where it is please?

**Comment by gdams** [comment]
it's all documented in https://github.com/docker-library/docs/pull/2008

Specifically:

### Using a different base Image

If you are using a distribution that we don't provide an image for you can copy the JDK using a similar Dockerfile to the one below:

```dockerfile
# Example
FROM <base image>
ENV JAVA_HOME=/opt/java/openjdk
COPY --from=%%IMAGE%%:11 $JAVA_HOME $JAVA_HOME
ENV PATH="${JAVA_HOME}/bin:${PATH}"
```

### Creating a JRE using jlink

On OpenJDK 11+, a JRE can be generated using `jlink`, see the following Dockerfile:

```dockerfile
# Example of custom Java runtime using jlink in a multi-stage container build
FROM %%IMAGE%%:11 as jre-build
# Create a custom Java runtime
RUN $JAVA_HOME/bin/jlink \
         --add-modules java.base \
         --strip-debug \
         --no-man-pages \
         --no-header-files \
         --compress=2 \
         --output /javaruntime
# Define your base image
FROM debian:buster-slim
ENV JAVA_HOME=/opt/java/openjdk
ENV PATH "${JAVA_HOME}/bin:${PATH}"
COPY --from=jre-build /javaruntime $JAVA_HOME
# Continue with your application deployment
RUN mkdir /opt/app
COPY japp.jar /opt/app
CMD ["java", "-jar", "/opt/app/japp.jar"]

**Comment by tellison** [comment]
Let's sit on this until `dockerhub.com/eclipse-temurin` is available then share more widely.

**Comment by gdams** [comment]
This will be shared in https://github.com/adoptium/blog.adoptium.net/pull/84
