### ISSUE TITLE
Missed platforms for the adoptopenjdk/openjdk11:jre-11.0.19_7 docker container

### ISSUE THREAD

**Issue by clenkiu** [adoptium/containers#400]
The last push of adoptopenjdk/openjdk11:jre-11.0.19_7 removed the linux/amd64 platform support.
https://hub.docker.com/layers/adoptopenjdk/openjdk11/jre-11.0.19_7/images/sha256-a8cde9480607d7b2d4cb7c3330c90b9df598a0c84832eb4041f50579f534a168?context=explore

Is that on purpose? What is the option to be used for a linux/amd64 platform.

I also see that the adoptopenjdk/openjdk11:latest still have it.

**Comment by karianna** [comment]
adoptopenjdk is considered deprecated (I'm not sure who's pushing those) - CC @gdams 

Please use the Eclipse Temurin images from DockerHub instead.

**Comment by gdams** [comment]
@clenkiu please migrate to `eclipse-temurin:11.0.19_7-jre`
