### ISSUE TITLE
[Bug]: Please support arm64 for 20-jre-alpine image

### ISSUE THREAD

**Issue by lukaszdutka** [adoptium/containers#408]
### Please add the exact image (with tag) that you are using

eclipse-temurin:20-jre-alpine

### Please add the version of Docker you are running

Docker version 20.10.13, build a224086

### What happened?

When I try to use image mentioned above, I am getting an error. It's unrelated to the real cause, but error is because of unsupported architecture on my computer.

From 
```
docker run --rm mplatform/mquery eclipse-temurin:20-jre-alpine
```

I got information, that this image supports only `linux/amd64` platform while i.e. `eclipse-temurin:20_36-jre-jammy` supports two more: `linux/arm64/v8` and `linux/ppc64le`

Comparing both Dockerfiles I can see that's the case:

https://github.com/adoptium/containers/blob/99918327b8e861a673f9d5edd58078eb54b50a1a/20/jre/ubuntu/jammy/Dockerfile.releases.full

https://github.com/adoptium/containers/blob/15919f7dd6a903f0f966f484461954dcf7e28620/20/jre/alpine/Dockerfile.releases.full

I managed to run 20-jre-alpine with a `--platform linux/amd64` flag, but it is significantly slower.

Is there any reason why this image is not supporting mac M1 chips natively?

**Comment by karianna** [comment]
See #158
