### ISSUE TITLE
Is eclipse-temurin:17.0.8_7-jre-alpine Supported in MacOS - ARM64 ? 

### ISSUE THREAD

**Issue by AmirMattarx** [adoptium/containers#420]
Based to the documentation it is mentioned that eclipse-temurin:17.0.8_7-jre-alpine supported in ARM64/v8 . 
but when trying it in my Mac Pro i get the bellow error : 

Could not build image: no matching manifest for linux/arm64/v8 in the manifest list entries 

Is it an issue or there is another version to use ?

**Comment by karianna** [comment]
We don't currently support Alpine for Aarch64 https://github.com/adoptium/containers/issues/158
