### ISSUE TITLE
Where can one download a signed SBOM for the Alpine container from?

### ISSUE THREAD

**Issue by iamvolvo** [adoptium/containers#421]
Say for `eclipse-temurin:17.0.8.1_1-jre-alpine` , DIGEST:sha256:83c4dd3e5481af358343dfffc74934bffc394b1a959bb143a0aafc1e88d4a202.

Thanks!

**Comment by karianna** [comment]
I don't believe we have signed SBOMs for this (yet).  CC @andrew-m-leonard

**Comment by andrew-m-leonard** [comment]
@iamvolvo hi, so no we don't have a container sbom per se, the jre itself will have an sbom available here: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.8.1%2B1/OpenJDK17U-sbom_x64_alpine-linux_hotspot_17.0.8.1_1.json
However, you maybe interested in trying the "docker sbom" facility: https://docs.docker.com/engine/sbom/
