### ISSUE TITLE
Java 21 was released on 19th September 2023

### ISSUE THREAD

**Issue by thatsIch** [adoptium/containers#424]
On https://hub.docker.com/_/eclipse-temurin the tag for Java 21 is missing,
though it was released a few days ago.

https://github.com/adoptium/temurin21-binaries is still missing a release (only prereleases are currently built and distributed).

This issue is intended as a reminder.

**Comment by karianna** [comment]
We're waiting for TCK access to complete this release.  Please visit our adoptium/adptium repo to track progress

**Comment by thatsIch** [comment]
I assume this issue is meant https://github.com/adoptium/adoptium/issues/248 ?

**Comment by paulholder** [comment]
> We're waiting for TCK access to complete this release. Please visit our adoptium/adoptium repo to track progress

In recent past releases there was a banner on the homepage linking to the GitHub checklist.  I've been checking daily, waiting for this to show up for 21, but it never did, so I had to google to find #248.
