### ISSUE TITLE
[Bug]: no match for platform in manifest

### ISSUE THREAD

**Issue by landsman** [adoptium/containers#425]
### Please add the exact image (with tag) that you are using

eclipse-temurin:17-jre-alpine

### Please add the version of Docker you are running

24.0.5

### What happened?

It's happen on my localhost, ARM CPU - M2 

### Relevant log output

```shell
ERROR: failed to solve: public.ecr.aws/docker/library/eclipse-temurin:17-jre-alpine: no match for platform in manifest sha256:186a8f15cb57b9e06115349b5a38467d4f29175513b762ead589e11e2a492e9e: not found
```

**Comment by karianna** [comment]
We don't support Alpine on Aarch64 yet

**Comment by landsman** [comment]
And is there an issue, plan for it?
