### ISSUE TITLE
Assess current set of dependencies in dockerfiles to determine if they are still needed

### ISSUE THREAD

**Issue by gdams** [adoptium/containers#458]
Initially discussed with @sxa via slack.

We don't believe that we need to ship libretls & zlib with Alpine anymore (we bundle zlib with the JDK)

All remaining dependencies should also be checked

**Comment by gdams** [comment]
## Alpine

| Name               | Still Required? | Comments                         |
|--------------------|-----------------|----------------------------------|
| bash               |  👍            |   Required for entrypoint.sh                               |
| fontconfig         |             |                                  |
| ttf-dejavu         |            |                                  |
| java-cacerts       |             |                                  |
| libretls           | ❌            |  not required                                |
| zlib               | ❌            |  bundled with the JDK                                |
| musl-locales       |             |                                  |
| musl-locales-lang  |              |                                  |
| binutils           |   👍          | required for jmod commands                                  |
| tzdata             |              |                                  |

**Comment by gdams** [comment]
## Centos

| Name           | Still Required? | Comments                                                             |
|----------------|-----------------|----------------------------------------------------------------------|
| gzip           | [ ]             |                                                                      |
| tar            | [ ]             |                                                                      |
| curl           | [ ]             | Required for historical reasons, see adoptium/containers#255, will be removed in 22         |
| wget           | [ ]             |                                                                      |
| tzdata         | [ ]             |                                                                      |
| openssl        | [ ]             |                                                                      |
| ca-certificates| [ ]             | Utilities for syncing Centos & OpenJDK CA certs, adoptium/containers#293 |
| binutils       | [ ]             | Required for jlink, see docker-library/openjdk#351                  |
| fontconfig     | [ ]             |                                                                      |

**Comment by gdams** [comment]
## UBI9-Minimal

| Name               | Still Required? | Comments                          |
|--------------------|--------------|-----------------------------------|
| gzip               |           |                                   |
| tar                |           |                                   |
| binutils           | 👍            | Required for jlink, see https://github.com/docker-library/openjdk/issues/351                                  |
| tzdata             |           |                                   |
| openssl            |           |                                   |
| wget               | 👍          |  Required to download JDK                                 |
| ca-certificates    | 👍         |  Utilities for syncing Centos & OpenJDK CA certs, https://github.com/adoptium/containers/issues/293                                 |
| fontconfig         |          |                                   |
| glibc-langpack-en  |          |                                   |

**Comment by gdams** [comment]
## Ubuntu (Focal and Jammy)

| Name               | Still Required? | Comments                                                                                     |
|--------------------|--------------|---------------------------------------------------------------------------------------------|
| curl           | 🔜             | Required for historical reasons, see adoptium/containers#255, will be removed in 22         |
| wget               | 👍          |  Required to download JDK                                 |
| fontconfig         |        |                                                                                             |
| ca-certificates    | 👍         |  Utilities for syncing Ubuntu & OpenJDK CA certs, https://github.com/adoptium/containers/issues/293      
| p11-kit             | 👍         |  Utilities for syncing Ubuntu & OpenJDK CA certs, https://github.com/adoptium/containers/issues/293                                                                                             |
| binutils           | 👍            | Required for jlink, see https://github.com/docker-library/openjdk/issues/351   |
| tzdata             |       |                                                                                             |
| locales            |         |           |

**Comment by sxa** [comment]
Ref Alpine, I suspect we can get rid of the requirement for bash without too much difficulty if it's only needed for `entrypoint.sh` - that's not a particularly complex script.

**Comment by gdams** [comment]
ping @dinogun as he might have some context as to why we ship UBI and Centos with the OpenSSL package

**Comment by dinogun** [comment]
@gdams The best explanation that I have is that we required OpenSSL at one point for OpenJ9 and this ended up being copied over for OpenJDK as well. Would be reasonable to remove it. Folks who really want OpenSSL, can always update their Dockerfiles to add it on top of the standard images.
