### ISSUE TITLE
[Bug]: eclipse-temurin 11.0.21 is not available on docker hub

### ISSUE THREAD

**Issue by marchof** [adoptium/containers#459]
### Please add the exact image (with tag) that you are using

eclipse-temurin:11.0.21

### Please add the version of Docker you are running

GitHub Action Runner

### What happened?

Eclipse Temurin 11.0.21 has been 3 weeks ago, also it looks like the Docker files in this repo have been updated to build this version. Unfortunatelly this version is not available on hub.docker.com:

https://hub.docker.com/_/eclipse-temurin/tags?page=1&name=11.0.21

**Comment by sxa** [comment]
The first 11.0.21 versions were published as tarballs on the 18th October (within a day of the upstream tags being available) and the docker publications generally don't appear until all platforms are ready. We are in the process of putting the PRs together to get the official docker images updated at the moment so they should be ready soon.

**Comment by marchof** [comment]
@sxa Thanks for the clarification and your great work! Sorry for the noise.
