### ISSUE TITLE
Alpine ARM64 support for JDK 11 or 17?

### ISSUE THREAD

**Issue by tspearconquest** [adoptium/containers#466]
Hello,

I noticed recently that ARM64 support has been added for the alpine distro for JDK21. Thank you for this, it is a huge development for us because our new employees are being assigned Mac M1 systems and are unable to run the eclipse-temurin Alpine containers without support for ARM64.

Since this was added to JDK21 on Alpine, I thought I would raise this issue to request the same support for both JDK11 and JDK17 on Alpine as we are working with some apps that are built with these containers on x86_64 and need to be able to build the apps so that they also can run on these M1 systems.

Thank you in advance for your consideration.

**Comment by sxa** [comment]
There was some discussion on this in https://github.com/adoptium/containers/issues/158#issuecomment-1637838315 - JDK11 on that platform has proved unreliable. I'd expect most users to be able to move up to 21, although we do have nightly builds for 17 available if you want to test them for your purposes.

**Comment by tspearconquest** [comment]
Thanks!
