### ISSUE TITLE
Request for eclipse-temurin 17 JRE Alpine images

### ISSUE THREAD

**Issue by bantao-kainos** [adoptium/containers#476]
The older versions of Alpine have some vulnerabilities.
Is the latest version of Alpine 3.19 relatively free from major vulnerabilities ?
But the official Docker JDK and JRE images are not yet generated with the latest Alpine 3.19 version.
We have a particular need for eclipse-temurin 17 JRE images with Alpine 3.19
What is the eta for the new images to be generated and made available ?

**Comment by gdams** [comment]
They will be made available shortly
