### ISSUE TITLE
The dockerhub_docs script isn't producing the correct output after this PR (it still only lists amd64

### ISSUE THREAD

**Issue by karianna** [adoptium/containers#49]
The dockerhub_docs script isn't producing the correct output after this PR (it still only lists amd64

_Originally posted by @karianna in https://github.com/adoptium/containers/issues/47#issuecomment-912073014_

**Comment by karianna** [comment]
This may not actually be a bug, but saving this here so I can investigate with more coffee later

**Comment by gdams** [comment]
That's because amd64 is the only available JRE on JDK11 right?

**Comment by karianna** [comment]
probably :-)
