### ISSUE TITLE
[Bug]: libjvm.so failed to load: j9vm29

### ISSUE THREAD

**Issue by NahidulIslam-Mylab** [adoptium/containers#490]
### Please add the exact image (with tag) that you are using

eclipse-temurin:17.0.8.1_1-jdk-jammy

### Please add the version of Docker you are running

Docker version 24.0.7, build afdd53b

### What happened?

Get this error in Mac M3 Pro Sonoma 14.3

### Relevant log output

```shell
2024-01-24 14:30:47 libjvm.so preloadLibrary(/opt/java/openjdk/lib/default/libj9vm29.so): /opt/java/openjdk/lib/default/libj9vm29.so: cannot enable executable stack as shared object requires: Invalid argument
2024-01-24 14:30:47 libjvm.so failed to load: j9vm29
```

**Comment by karianna** [comment]
@NahidulIslam-Mylab You'll want to try the latest 17.0.10 image coming out next week.  Is there a reason why you're not using Mac OS X Aarch64 build natively?  Also is that Docker for Aarch64 with an Arch64 JVM or are you going through Rosetta?

**Comment by NahidulIslam-Mylab** [comment]
@karianna we are using custom images which are build on x86 and there is  no Aarch64 for them. Those are build by different team and we have no control over that. But, I think apple is going to fix that in their next release.

**Comment by NahidulIslam-Mylab** [comment]
Apple is going to fix that in the next release of macOS Sonoma. Hence, closing it.
