### ISSUE TITLE
[Bug?]: removal of bash breaks downstream images

### ISSUE THREAD

**Issue by josephlbarnett** [adoptium/containers#496]
### Please add the exact image (with tag) that you are using

eclipse-temurin:11-jre-alpine

### Please add the version of Docker you are running

Docker version 24.0.6, build ed223bc

### What happened?

Rebuilt an image that was based `FROM eclipse-temurin:11-jre-alpine` and started to get the attached failure.
Was able to work around this by changing a `bash` to an `sh` in our `CMD`, but did not expect this to disappear from beneath us.  Are these sorts of changes things we should expect and we should pin to a more specific upstream tag, or is there a better recommended way of handling them (are there release notes we can subscribe to somewhere that would list out potentially breaking changes like this?)?

Thanks, appreciate what you do!

### Relevant log output

```shell
/__cacert_entrypoint.sh: exec: line 30: bash: not found
```

**Comment by karianna** [comment]
Came from https://github.com/adoptium/containers/pull/460/files - that change should have been release note'd but not sure where:  @gdams do you know where we output change notes like that?

**Comment by moritzschmitz-oviva** [comment]
Yup, also took me by surprise just now.

**Comment by moritzschmitz-oviva** [comment]
@gdams Is there a pull request you could link perhaps? Or another issue?
