### ISSUE TITLE
Add Oracle Linux based containers

### ISSUE THREAD

**Issue by Subrhamanya** [adoptium/containers#500]
### Please add the exact image (with tag) that you are using

eclipse-temurin 8/11/17/21

### Please add the version of Docker you are running

docker latest

### What happened?

Is there any possibility for the adoptium team to provide the docker java jdk/jre image built on top of oraclelinux?

I have seen for alpine/centos etc...
![image](https://github.com/adoptium/containers/assets/36793516/5ebe5e2f-3203-4d84-b898-9e9bfedf5220)

I appreciate the response from adoptium team. This really helps the community.

**Comment by karianna** [comment]
@Subrhamanya we'll be going with a broader base level approach see https://github.com/adoptium/installer/issues/501

**Comment by gdams** [comment]
@Subrhamanya is there any reason why you couldn't do something like this?

```dockerfile
FROM oraclelinux:9
ENV JAVA_HOME=/opt/java/openjdk
COPY --from=eclipse-temurin:21 $JAVA_HOME $JAVA_HOME
ENV PATH="${JAVA_HOME}/bin:${PATH}"
```

**Comment by sxa** [comment]
> @Subrhamanya we'll be going with a broader base level approach see [adoptium/installer#501](https://github.com/adoptium/installer/issues/501)

@karianna That is for rpm/deb installers and not our "official" containers on dockerhub.

**Comment by karianna** [comment]
> > @Subrhamanya we'll be going with a broader base level approach see [adoptium/installer#501](https://github.com/adoptium/installer/issues/501)
> 
> @karianna That is for rpm/deb installers and not our "official" containers on dockerhub.

True! We'll need a clear matrix for each.

**Comment by gdams** [comment]
Closing this for now. Please feel free to reopen if this is still a requirement
