### ISSUE TITLE
Ubuntu Noble flavor?

### ISSUE THREAD

**Issue by poikilotherm** [adoptium/containers#532]
### Please add the exact image (with tag) that you are using

eclipse-temurin:17-jre

### Please add the version of Docker you are running

26.0.0

### What happened?

I cannot yet use Ubuntu Noble (24.04 LTS), which is going to be released on April 25, for pre-release testing of my application.

Would a pull request to add Noble to `config/hotspot.yml` be welcome?

**Comment by karianna** [comment]
@poikilotherm That would be good thank you.

**Comment by sxa** [comment]
Adding pmc agenda label based on my comment in the PR so it should get discussed next week 😀

**Comment by gdams** [comment]
Noting that Ubuntu Noble goes GA on the 25th April.

**Comment by tellison** [comment]
The PMC discussed this request on 24 March. The conclusion was that temurin will continue to support [Docker official base images](https://docs.docker.com/trusted-content/official-images/) and we there fore expect Noble to be supported in the corresponding release cycle.

**Comment by trandersen-ufst** [comment]
> The PMC discussed this request on 24 March. The conclusion was that temurin will continue to support [Docker official base images](https://docs.docker.com/trusted-content/official-images/) and we there fore expect Noble to be supported in the corresponding release cycle.

@tellison I am trying to find out when that will be for my team to prioritize.  If I understand https://adoptium.net/support/#_release_roadmap correctly, that would be up to three weeks after the OpenJDK project releases a security update.  This has just happened, so next time is in July and therefore the 24.04 docker images can be expected to show up in the middle of August.  Is this correct?

**Comment by tellison** [comment]
> I am trying to find out when that will be for my team to prioritize. If I understand https://adoptium.net/support/#_release_roadmap correctly, that would be up to three weeks after the OpenJDK project releases a security update. This has just happened, so next time is in July and therefore the 24.04 docker images can be expected to show up in the middle of August. Is this correct?

In theory, that logic is correct. However, we discussed in the PMC the ability to do an out of cycle publication of Noble-based official images.

The plan is to run our Temurin AQAvit tests on a Noble image, and if all looks good we would go ahead and publish a new Temurin official image based upon that. The tests should not take too long, but I can't give you a specific timeline to completion since the work is not yet scheduled.

You can follow the request to test as https://github.com/adoptium/aqa-tests/issues/5271 which is a prereq to updating the dockerfiles etc.

**Comment by trandersen-ufst** [comment]
@tellison Thank you for the full explanation.   This sound like a good way to handle the situation.  I have subscribed to the request to test as suggested.
