### ISSUE TITLE
`slim` container jdk releases

### ISSUE THREAD

**Issue by srbala** [adoptium/containers#54]
It looks like slim version of container has been missing. Any plans to implement? I would happy to work on a PR if needed

**Comment by karianna** [comment]
See #1 - we're still defining what the final supported set will be. What is your definition of slim?

**Comment by srbala** [comment]
> What is your definition of slim?
* **`Base OS + JDK or JRE + Required packages`**
* Smaller in container image size
* Less number of packages in container image - better for secuirty, faster download

@karianna you can close the issue or keep it for tracking as needed

**Comment by marchof** [comment]
I typically used `alpine-slim` for small container sizes. Small containers are essential for fast serverless startups.

**Comment by gdams** [comment]
> I typically used alpine-slim for small container sizes. Small containers are essential for fast serverless startups.

@marchof is there any reason that you don't use jlink to create a far smaller base image? For example, if a target application depends only on the `java.base` module then a Docker image with Alpine Linux and a Java runtime with just that module and the server VM fits in 38 MB.

**Comment by marchof** [comment]
@gdams Yes, in my (probably very specific case) I need the full JDK, as I don't know which code will be executed at runtime. I'm talking about the Java sandbox backend of javaalmanac.io, see for example: https://javaalmanac.io/features/records/

The slim images are typically around 200MB, while the default images are almost 300 MB.

But I admit that this is maybe a very specific use case

**Comment by srbala** [comment]
@gdams is `jlink` ported to `jdk8`? Using `jdk11` need a major upgrade path for us and we are not there yet.

**Comment by gdams** [comment]
> @gdams is jlink ported to jdk8? Using jdk11 need a major upgrade path for us and we are not there yet.

Sorry, I missed that you were on 8, how about an alpine JRE?

**Comment by srbala** [comment]
@marchof was using alpine, I am using [**`ubi-minimal-slim`**](https://github.com/AdoptOpenJDK/openjdk-docker/blob/master/8/jdk/ubi-minimal/Dockerfile.hotspot.releases.slim)

**Comment by srbala** [comment]
Closing this issue to continue the discussion in https://github.com/adoptium/containers/issues/1#issuecomment-919707778
