### ISSUE TITLE
armv7 images

### ISSUE THREAD

**Issue by bbernhard** [adoptium/containers#55]
Hi,

previously I was using the [Adoptopenjdk](https://hub.docker.com/_/adoptopenjdk) images, but as they are not longer maintained, I switched to the `eclipse-temurin` images. One thing I noticed however is, that there are no armv7 images. Are there any plans to support armv7 as well, or will support for that architecture completely dropped? 

Many thanks,
Bernhard

**Comment by karianna** [comment]
We are supporting armv7 AFAICT - I think we just need to get the Java binaries out before we creat the containers for them.

**Comment by karianna** [comment]
These have now been released

**Comment by bbernhard** [comment]
Wow, that was fast - many thanks for taking care of that so fast. Very much appreciated!

just to be sure: I just checked the images on dockerhub and couldn't see any images with `armv7` - but I guess this probably takes a bit until the new images are available, right?

**Comment by karianna** [comment]
That's correct, they need verifying etc upstream

**Comment by CodingKoopa** [comment]
Hi! I have a couple of things about the armv7 images that I'm hoping to get cleared up:
- What is the difference between, say, the `16` tag and the `16-focal` tag? They appear to serve different manifests, but I would expect the Focal image (Ubuntu) to be the "default".
- Will armv7 images be coming to the `16` tag? I only see them associated with the `17` tag.

Much thanks!

**Comment by karianna** [comment]
@gdams do you know the difference here?

**Comment by gdams** [comment]
The two tags should be identical. As for JDK16 we will be shipping arm32 very soon.
