### ISSUE TITLE
[Bug]: not able to build the image 

### ISSUE THREAD

**Issue by sravula84** [adoptium/containers#561]
### Please add the exact image (with tag) that you are using

eclispe-temurin:jdk17-jammy

### Please add the version of Docker you are running

24.0.5

### What happened?

trying to build docker image from my local machine ( here is the dockerfile reference)- https://github.com/adoptium/containers/blob/057e5aa7581e96b8a2334290e750b329d62abfdf/17/jdk/ubuntu/jammy/Dockerfile

error :

 > [ 5/11] RUN DEBIAN_FRONTEND=noninteractive apt-get update -y &&     DEBIAN_FRONTEND=noninteractive apt-get install -y apt-utils &&     DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends unzip:
0.984 Get:1 http://ports.ubuntu.com/ubuntu-ports jammy InRelease [270 kB]
1.786 Err:1 http://ports.ubuntu.com/ubuntu-ports jammy InRelease
1.786   At least one invalid signature was encountered.
1.846 Get:2 http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease [119 kB]
1.989 Err:2 http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease
1.989   At least one invalid signature was encountered.
2.088 Get:3 http://ports.ubuntu.com/ubuntu-ports jammy-backports InRelease [109 kB]
2.290 Err:3 http://ports.ubuntu.com/ubuntu-ports jammy-backports InRelease
2.290   At least one invalid signature was encountered.
2.371 Get:4 http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease [110 kB]
2.539 Err:4 http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease
2.539   At least one invalid signature was encountered.
2.544 Reading package lists...
2.553 W: GPG error: http://ports.ubuntu.com/ubuntu-ports jammy InRelease: At least one invalid signature was encountered.
2.553 E: The repository 'http://ports.ubuntu.com/ubuntu-ports jammy InRelease' is not signed.
2.553 W: GPG error: http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease: At least one invalid signature was encountered.
2.553 E: The repository 'http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease' is not signed.
2.553 W: GPG error: http://ports.ubuntu.com/ubuntu-ports jammy-backports InRelease: At least one invalid signature was encountered.
2.553 E: The repository 'http://ports.ubuntu.com/ubuntu-ports jammy-backports InRelease' is not signed.
2.553 W: GPG error: http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease: At least one invalid signature was encountered.
2.553 E: The repository 'http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease' is not signed.
------

### Relevant log output

```shell
> [ 5/11] RUN DEBIAN_FRONTEND=noninteractive apt-get update -y &&     DEBIAN_FRONTEND=noninteractive apt-get install -y apt-utils &&     DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends unzip:
0.984 Get:1 http://ports.ubuntu.com/ubuntu-ports jammy InRelease [270 kB]
1.786 Err:1 http://ports.ubuntu.com/ubuntu-ports jammy InRelease
1.786   At least one invalid signature was encountered.
1.846 Get:2 http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease [119 kB]
1.989 Err:2 http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease
1.989   At least one invalid signature was encountered.
2.088 Get:3 http://ports.ubuntu.com/ubuntu-ports jammy-backports InRelease [109 kB]
2.290 Err:3 http://ports.ubuntu.com/ubuntu-ports jammy-backports InRelease
2.290   At least one invalid signature was encountered.
2.371 Get:4 http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease [110 kB]
2.539 Err:4 http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease
2.539   At least one invalid signature was encountered.
2.544 Reading package lists...
2.553 W: GPG error: http://ports.ubuntu.com/ubuntu-ports jammy InRelease: At least one invalid signature was encountered.
2.553 E: The repository 'http://ports.ubuntu.com/ubuntu-ports jammy InRelease' is not signed.
2.553 W: GPG error: http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease: At least one invalid signature was encountered.
2.553 E: The repository 'http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease' is not signed.
2.553 W: GPG error: http://ports.ubuntu.com/ubuntu-ports jammy-backports InRelease: At least one invalid signature was encountered.
2.553 E: The repository 'http://ports.ubuntu.com/ubuntu-ports jammy-backports InRelease' is not signed.
2.553 W: GPG error: http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease: At least one invalid signature was encountered.
2.553 E: The repository 'http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease' is not signed.
------
```

**Comment by gdams** [comment]
This looks like a glitch in the Ubuntu package manager, is it still failing today?

**Comment by gdams** [comment]
I'm going to close this for now. Feel free to reopen it if it's still an issue
