### ISSUE TITLE
[Bug]: Not able to pull images from this repository

### ISSUE THREAD

**Issue by webmutation** [adoptium/containers#565]
### Please add the exact image (with tag) that you are using

eclipse-temurin:17-jre-alpine

### Please add the version of Docker you are running

26.1.3

### What happened?

For the last couple of days we are unable to fetch the eclipse-temurin images. 

ERRO[0001] Error while retrieving image from cache: eclipse-temurin:17-jre-alpine TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

We are using a Pro account to pull these images.

**Comment by gdams** [comment]
As these images are official images you'll need to raise a big with Docker to report issues with rate limits I'm afraid. I suggest trying here https://github.com/docker-library/official-images/issues
