### ISSUE TITLE
Support for arm64, temurin 17 and alpine?

### ISSUE THREAD

**Issue by victornoel** [adoptium/containers#566]
### Please add the exact image (with tag) that you are using

eclipse-temurin:17-jdk-alpine

### Please add the version of Docker you are running

Docker version 26.1.3, build b72abbb6f0

### What happened?

I noticed that for arm64, there is support for
- temurin 17 and ubuntu (focal)
- temurin 21 and alpine

But no support for temurin 17 and alpine.

Is there any way to add it?

Thank you

**Comment by karianna** [comment]
See https://github.com/adoptium/containers/issues/466 - Java 17 on Alpine isn't really considered to be production ready/stable.

**Comment by victornoel** [comment]
@karianna makes sense, thank you for the feedback and sorry for missing that old ticket :)

**Comment by karianna** [comment]
All good, I/we totally lose sight of old tickets decisions, and we work here ;-)
