### ISSUE TITLE
eclipse-temurin:17-jre-alpine vulnerabilities

### ISSUE THREAD

**Issue by zopahima** [adoptium/containers#576]
eclipse-temurin:17-jre-alpine image contains multiple old vulnerabilities, is there any plan to address them in the near future? when can expected to get a patched version?
vul scan taken by trivy scanner.

![image](https://github.com/adoptium/containers/assets/164059200/a2e62a88-444c-4170-8981-e2bdb7e01fb3)

**Comment by karianna** [comment]
The base layer gets updated by DockerHub, you can also tdnf update in the mean time.

**Comment by zopahima** [comment]
@karianna  Already did it here, I was referred to adoptium.
See - https://github.com/docker/roadmap/issues/675

**Comment by omni-htg** [comment]
@zopahima As you can see in DockerHub, the last `alpine:3.19` was built [5 months ago](https://hub.docker.com/layers/library/alpine/3.19/images/sha256-6457d53fb065d6f250e1504b9bc42d5b6c65941d57532c072d929dd0628977d0?context=explore), and the image `eclipse-temurin:17-jre-alpine` you're pointing to [was built after that](https://hub.docker.com/layers/library/eclipse-temurin/17-jre-alpine/images/sha256-82fc7720a42cef9e24c9fc61616bee7e9c0429a9346835042520409b47f064d1?context=explore) using the latest 17.0.11+9 version.
So unless there's an update to alpine 3.19 or a new openjdk version, the image is not getting updated.
Perhaps the folks at Alpine could see this and trigger a bump on 3.19, [give them a try](https://github.com/alpinelinux/docker-alpine/issues).

**Comment by karianna** [comment]
> @karianna Already did it, I was referred to adoptium. See - [docker/roadmap#675](https://github.com/docker/roadmap/issues/675)

I _think_ that's a different place to DockerHub - but I appreciate that this is frustrating, we need a better round robin policy here.

**Comment by zopahima** [comment]
@omni-htg Thanks!! Where can I track alpine merges into temurin? How can I track when it gets into DockerHub?
