### ISSUE TITLE
java 21 default garbage collector should be Garbage-First (G1)?

### ISSUE THREAD

**Issue by MarekUniq** [adoptium/containers#597]
Hi!

Several references can be found online indicating that **Garbage-First (G1)** is the default garbage collector in Java 21, and it has been the default setting **since Java 9**.

But if I take the following image:
`FROM eclipse-temurin:21-jre-alpine
`

and run the following code without any arguments OR with argument -XX:+UseSerialGC:
```
import java.lang.management.GarbageCollectorMXBean;
import java.lang.management.ManagementFactory;
import java.util.List;

public class GCBeanNames {

  public static void main(String[] args) {
    List<GarbageCollectorMXBean> beanList = ManagementFactory.getGarbageCollectorMXBeans();
    for (GarbageCollectorMXBean bean : beanList) {
      System.out.println(String.format("GarbageCollectorMXBean.getName(): [%s]", bean.getName()));
    }
  }
}
```

then the result is the same for both cases:
```
GarbageCollectorMXBean.getName(): [Copy]
GarbageCollectorMXBean.getName(): [MarkSweepCompact]
```

and when I run the same code with argument:
`...  -XX:+UseG1GC ...`

then the result is:
```
GarbageCollectorMXBean.getName(): [G1 Young Generation]
GarbageCollectorMXBean.getName(): [G1 Concurrent GC]
GarbageCollectorMXBean.getName(): [G1 Old Generation]
```

The preceding information indicates that the default garbage collector is the Serial Collector (-XX:+UseSerialGC).

Question: "Is the claim that G1 is the default garbage collector incorrect, or what could be the reason that the G1 garbage collector is not used by default?"

Regards
Marek

**Comment by karianna** [comment]
Please see https://learn.microsoft.com/en-us/azure/developer/java/containers/overview#understand-jvm-default-ergonomics
