### ISSUE TITLE
[Bug]: Error building with temurin-17: adduser not found

### ISSUE THREAD

**Issue by haphazardeous** [adoptium/containers#606]
### Please add the exact image (with tag) that you are using

eclipse-temurin:17

### Please add the version of Docker you are running

docker:20.10.16

### What happened?

Our Dockerfile contains the following 

```
FROM eclipse-temurin:17
RUN adduser --system --group spring
USER spring:spring
.
.
.
```

This has been working fine but this morning we couldn't run any of our builds as all of them failed with the following 

```
#5 [2/5] RUN adduser --system --group spring
#5 sha256:e77de5906a7a076deb83aff9a4beb9a33be7a535eeab19f1b4904f5a100a460e
#5 0.170 /bin/sh: 1: adduser: not found
#5 ERROR: executor failed running [/bin/sh -c adduser --system --group spring]: exit code: 127
------
 > [2/5] RUN adduser --system --group spring:
------
executor failed running [/bin/sh -c adduser --system --group spring]: exit code: 127
```

Can anyone help on this? 

Many thanks,
Vedat

**Comment by LaSylv** [comment]
Same error, with addgroup

**Comment by LaSylv** [comment]
I circumvented the problem by using groupadd

It is not a dropin replacement but is pretty easy to do

**Comment by david-hel** [comment]
Same error when trying to run `RUN pip3 install --upgrade pip` on temurin-17 after todays update.

**Error:**
`ERROR: failed to solve: process "/bin/sh -c pip3 install --upgrade pip" did not complete successfully: exit code: 1`

**Comment by hungchu0912** [comment]
+1 with addgroup

**Comment by haphazardeous** [comment]
I tried openjdk-java:17 and the issue persisted. Might not be related to temurin

**Comment by pcdavid** [comment]
From what I understand, [this commit](https://github.com/adoptium/containers/commit/d762761bff59ad4ee3bacf89050e2081e5464c65) from 2 week ago changed the default base image from Ubuntu focal (20.04) to Ubuntu noble (24.04).

The official `ubuntu:focal` image used to have `useradd` installed by default, but `ubuntu:noble` does not:

![Capture d’écran du 2024-07-23 12-00-18](https://github.com/user-attachments/assets/c9f7f35e-6228-4121-9426-fe75b56c6295)

**Comment by darioseidl** [comment]
With `eclipse-temurin:17-jre-focal` instead of `eclipse-temurin:17-jre` as base image, `addgroup` and `adduser` work again.

**Comment by gdams** [comment]
Hi all, thanks for raising this issue, this is due to the change of the latest tag from jammy to noble. As @darioseidl correctly points out you can stay on the older Ubuntu base using `eclipse-temurin:17-focal` or `eclipse-temurin:17-jammy`

**Comment by haphazardeous** [comment]
Thanks for all the help everyone. I’m now closing the issue.
