### ISSUE TITLE
[Bug]: laest eclipse-temurin:22-jdk already has user and group at id 1000

### ISSUE THREAD

**Issue by andrewdibiasio6** [adoptium/containers#613]
### Please add the exact image (with tag) that you are using

eclipse-temurin:22-jdk

### Please add the version of Docker you are running

Docker version 25.0.3, build 4debf41

### What happened?

When using latest eclipse-temurin:22-jdk `sha256:f4fed76bbdea846ee9b0cbacdd15d3fba167e43f54ffb5a1aed619ea289f8044` our dockerFile file contains:

```
FROM {aws_pullthrough}.dkr.ecr.us-east-1.amazonaws.com/docker-hub/library/eclipse-temurin:22-jdk
RUN \
    groupadd app --gid 1000 && \
    useradd app --uid 1000 --gid 1000
```
We notice an existing user and group at id 1000:

```
group: ubuntu x 
user: ubuntu
```

### Relevant log output
```shell
useradd: UID 1000 is not unique
```

```shell
failed to solve: process "/bin/sh -c set -xeu &&     groupadd migration --gid 1000 &&     useradd migration --uid 1000 --gid 1000" did not complete successfully: exit code: 4
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c set -xeu &&     groupadd migration --gid 1000 &&     useradd migration --uid 1000 --gid 1000" did not complete successfully: exit code: 4
```

**Comment by andrewdibiasio6** [comment]
Ah likely do to switch to ubuntu-24-04 https://askubuntu.com/questions/1513927/ubuntu-24-04-docker-images-now-includes-user-ubuntu-with-uid-gid-1000

**Comment by gdams** [comment]
> Ah likely do to switch to ubuntu-24-04 https://askubuntu.com/questions/1513927/ubuntu-24-04-docker-images-now-includes-user-ubuntu-with-uid-gid-1000

That's correct, if you'd prefer to continue using 22.04 you can use `eclipse-temurin:22-jdk-jammy`

**Comment by veita** [comment]
Same problem with `eclipse-temurin:21.0.8_9-jre-noble`. This change possibly affects any containerized Java application that relies on a dedicated non-system user.
