### ISSUE TITLE
[Bug]: 8-jdk still builds on Jammy - intentional?

### ISSUE THREAD

**Issue by vlkl-sap** [adoptium/containers#615]
### Please add the exact image (with tag) that you are using

eclipse-temurin:8-jdk

### Please add the version of Docker you are running

-

### What happened?

Hello,
it looks like `11-jdk`, `17-jdk`, and `21-jdk` now build on Noble, but `8-jdk` still builds on Jammy. Is this intentional?
The lack of consistency is causing extra complexity here. Unfortunately, we are consuming `eclipse-temurin` not directly but via the `maven` image, which has no os-version variants.
Thanks!

**Comment by gdams** [comment]
This should be updated now, we had a slight delay publishing our JDK8u updates
