### ISSUE TITLE
[Bug]: curl & libcurl are missing from all the 22-jdk Ubuntu images

### ISSUE THREAD

**Issue by Poundex** [adoptium/containers#630]
### Please add the exact image (with tag) that you are using

eclipse-temurin:22-jdk

### Please add the version of Docker you are running

Docker version 27.1.1, build 63125853e3

### What happened?

Neither the curl program or its libcurl library seem to be present in the Ubuntu JDK 22 images. I checked both the jammy and the noble variants. 

### Relevant log output

```shell
Noticed library was failing:
Caused by: java.lang.RuntimeException: Could not start process: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory

Went to see if library was in non-standard location and needed symlinking, but doesn't seem to be present at all:
ubuntu@093535e4b6e0:/$ find -name libcurl.so*
find: ‘./var/cache/ldconfig’: Permission denied
find: ‘./var/cache/apt/archives/partial’: Permission denied
find: ‘./etc/ssl/private’: Permission denied
find: ‘./proc/tty/driver’: Permission denied
find: ‘./root’: Permission denied

Checked if the curl binary was present:
ubuntu@093535e4b6e0:/$ curl
bash: curl: command not found
```

**Comment by gdams** [comment]
We intentionally removed curl from the image in 22 as we were using wget by default. https://github.com/adoptium/containers/blob/3af43b469027c0c2241bf6dd066ec93ef2b9ff66/docker_templates/ubuntu.Dockerfile.j2#L10-L13

I wonder if we need to add curl back then if it's breaking things. Have you got a simple reproducer file?

**Comment by gdams** [comment]
After discussing this with the PMC, we have decided that curl should not be added back to the JKDK22 Docker Images. While I understand this is an inconvenience, we have to make these breaking changes every so often. Is it possible for you to add curl back to your Dockerfile manually?
