### ISSUE TITLE
`docker pull adoptopenjdk/openjdk11-openj9:latest` gives `no matching manifest for linux/amd64 in the manifest list entries`

### ISSUE THREAD

**Issue by MPV** [adoptium/containers#65]
A clone of issue https://github.com/adoptium/temurin-build/issues/2719

---

**What are you trying to do?**

`docker pull adoptopenjdk/openjdk11-openj9:latest`

**Expected behaviour:**

image pulled

**Observed behaviour:**

```
$ docker pull adoptopenjdk/openjdk11-openj9:latest
latest: Pulling from adoptopenjdk/openjdk11-openj9
no matching manifest for linux/amd64 in the manifest list entries
```

**Any other comments:**

The `latest` image (published 2 hours ago) seems to only be published for the `linux/ppc64le` OS/arch as per:
https://hub.docker.com/layers/adoptopenjdk/openjdk11-openj9/latest/images/sha256-77fc0dd8ea293637ca1631752ffcb80dd9e3928328823c562838200ca4d4240d?context=explore

**Comment by karianna** [comment]
Eclipse Adoptium is no longer providing images for OpenJ9 builds, please see https://developer.ibm.com/languages/java/semeru-runtimes/ for the successor to adoptopenjdk openj9 builds

**Comment by AdamBrousseau** [comment]
Dup eclipse-openj9/openj9#13534
