### ISSUE TITLE
Support alpine based images (Java 8, 11, 16, 17)

### ISSUE THREAD

**Issue by llamahunter** [adoptium/containers#72]
The previous adoptopenjdk project supported compact alpine base images. Please restore support for them, at least using musl, if not glibc.

**Comment by tellison** [comment]
This is being discussed on the [Temurin build issue 2688](https://github.com/adoptium/temurin-build/issues/2688).

You can follow the progress of each [Java 17 platform release here](https://github.com/adoptium/adoptium/issues/74#issue-992857422).

**Comment by karianna** [comment]
- [ ] Java 8
- [ ] Java 11
- [x] Java 16
- [x] Java 17

**Comment by christophsturm** [comment]
will the alpine images also support arm64?

**Comment by karianna** [comment]
> will the alpine images also support arm64?

Not at this stage, we'd be happy to accept a contribution for this.

**Comment by christophsturm** [comment]
cool. where would i start when i would like to contribute this?

**Comment by karianna** [comment]
Do you have access to any Linux ARM systems?

**Comment by christophsturm** [comment]
i have a m1 mac.

**Comment by karianna** [comment]
OK, that might work?  See if you can get VirtualBox or Parallels running, and start-up an Alpine ARM docker image (https://hub.docker.com/_/alpine).

**Comment by christophsturm** [comment]
building alpine based images arm64 images works fine even on macos, but It seems the temurin update scripts (`update_all.sh` and others) work only on linux. so I will probably need to try it on parallels.

**Comment by devoto13** [comment]
Isn't the problem here is that there are no arm64 binaries for Alpine available? https://adoptium.net/releases.html?variant=openjdk17&jvmVariant=hotspot

This is the most closely related issue which I've found upstream - https://github.com/adoptium/temurin-build/issues/2497.

**Comment by llamahunter** [comment]
I think this arm64 stuff is off topic for this issue?  
Still hoping for java 8 alpine support soon.

**Comment by llamahunter** [comment]
Is an alpine version of java 8 now available? The other github issue I was tracking for this was recently closed, but I don't see the image listed on https://github.com/docker-library/docs/blob/master/eclipse-temurin/README.md#supported-tags-and-respective-dockerfile-links

**Comment by llamahunter** [comment]
I still don't see a jdk8 alpine image.

**Comment by karianna** [comment]
We're still working on that one

Cheers,
Martijn

**Comment by gounthar** [comment]
I have several `aarch64` machines available with Docker.
How can I help getting those alpine jdk8+ images published?

**Comment by gdams** [comment]
Alpine images for JDK8u will be available once https://github.com/docker-library/official-images/pull/12000 is merged

**Comment by gounthar** [comment]
Thanks.
When will we see the results on [Docker Hub](https://hub.docker.com/_/eclipse-temurin?tab=tags&page=1&name=alpine)?

**Comment by DRoppelt** [comment]
@gounthar you mean [this one](https://hub.docker.com/layers/eclipse-temurin/library/eclipse-temurin/8u322-b06-jdk-alpine/images/sha256-a36a793f4b0ca45c9425f1cb6d4597b4421bc6e76440bb7725c25ec00a3a8600?context=explore)?

**Comment by gounthar** [comment]
Yes @DRoppelt .

**Comment by gounthar** [comment]
Any news for archs different from `linux/amd64`?
Thanks.

**Comment by gounthar** [comment]
@karianna / @gdams I can see Adoptium supplies `aarch64` Docker [images](https://hub.docker.com/r/arm64v8/eclipse-temurin/tags?page=1) (Ubuntu Focal, Centos 7), but I can't see any Alpine nor Debian images.
What is the blocking point?
How can I help?
Thanks.

**Comment by gdams** [comment]
@gounthar we're tracking Alpine in https://github.com/adoptium/containers/issues/158

There is currently no plan for Debian (see https://blog.adoptium.net/2021/08/using-jlink-in-dockerfiles/ for more information on how to copy the JDK into a base image of your choice)
