### ISSUE TITLE
Support to other OS

### ISSUE THREAD

**Issue by RubenRibGarcia** [adoptium/containers#75]
Hello,

I would like to ask if you are accepting pull requests to make available more OS ? For example Debian ?

**Comment by gdams** [comment]
@RubenRibGarcia can you not copy the JDK from the ubuntu image? Something like this?

```dockerfile
FROM debian
ENV JAVA_HOME=/opt/java/openjdk
COPY --from=eclipse-temurin:11 $JAVA_HOME $JAVA_HOME
ENV PATH="${JAVA_HOME}/bin:${PATH}"
# Continue with your application deployment
RUN mkdir /opt/app
COPY japp.jar /opt/app
CMD ["java", "-jar", "/opt/app/japp.jar"]
```

**Comment by RubenRibGarcia** [comment]
@gdams That would work yes :)

But while I was checking the code from this repo, I saw that it has a few functions for other OSes instead of Ubuntu, CentOS and Windows. There are functions for Debian,Debian-slim,Ubi-8, etc... that by the look of it, and by doing some minor testing on my own, by adding more configurations for `hotspot.config` we could generate more images for more OSes than the ones that are already present at this repo.

Here is the procedure that generated successfully a eclipse-temurin image from JDK 17 extend from a `debian:buster` and `debian-slim:buster`. (Because of `print_debian_ver()` and `print_debianslim_ver()` function at `dockerfile_functions.sh`)
1. I added to `hotspot.config`, `debian` and `debianslim` to `OS:` 
2. Next I added something like 
```
Build: releases
Type: full
Architectures: aarch64 x86_64 ppc64le
OS_Family: linux
Directory: 17/jdk/debian

...

Build: releases
Type: full
Architectures: aarch64 x86_64 ppc64le
OS_Family: linux
Directory: 17/jdk/debianslim
```

I was trying to develop an alternative way to generate more images for more OSes "flavours" (like `debian:buster`, `debian:bullseye`, `ubuntu:21.10`, etc) by extending the already known structure of the `hotspot.config` and probably changing the initial part to fetch the values to generated this Dockerfiles (this is just a thing I'm still testing of course).

So I will ask if there an objective for this repository to generate as many images for many OSes flavour, or it will keep doing it for the Ubuntu, CentOS and Windows ?

**Comment by gdams** [comment]
> So I will ask if there an objective for this repository to generate as many images for many OSes flavour, or it will keep doing it for the Ubuntu, CentOS and Windows ?

The code was all carried over from the AdoptOpenJDK repo. Unfortunately, things got out of hand there and we ended up supporting far too many distros. We are also under much stricter guidelines because we build in the official Docker Hub space. My current preference would be to keep encouraging people to use the `COPY` function unless there is a genuine reason blocking them from doing so.

**Comment by RubenRibGarcia** [comment]
I believe :) .

Thank you very much for your time and help, I will close this issue.
