### ISSUE TITLE
Docker image for JRE

### ISSUE THREAD

**Issue by erasmas** [adoptium/containers#77]
Thanks for all the work on producing solid Docker containers for OpenJDK. 🙌🏼 

Will there be Docker images for JRE based on JDK 17? I used to rely on JRE and `eclipse-temurin:11-jre` specifically, but for JDK 17 there are only images that include full JDK. Will it be up to users to rely on `jlink` and build their own containers for JRE?

**Comment by jerboaa** [comment]
> Will there be Docker images for JRE based on JDK 17? I used to rely on JRE and `eclipse-temurin:11-jre` specifically, but for JDK 17 there are only images that include full JDK. Will it be up to users to rely on `jlink` and build their own containers for JRE?

Yes. See https://github.com/adoptium/temurin-build/issues/2683 Specifically: https://github.com/adoptium/temurin-build/issues/2683#issuecomment-905540240

Documentation: https://blog.adoptium.net/2021/08/using-jlink-in-dockerfiles/

**Comment by KevinAtSesam** [comment]
@jerboaa Hey, thanks for sharing the tutorial. If possible, you should write a second tutorial that shows users how they can use `ALL-MODULE-PATH` to quickly make their own JRE within five minutes. At first, I was really struggling to get all the available modules, but still saving on space by cutting out all the sdk related components.

### Image from my work
```
# Java runtime that we'll use to create a JRE
FROM eclipse-temurin:17-centos7 as jre-build

# Create a custom Java runtime
RUN $JAVA_HOME/bin/jlink \
         --add-modules ALL-MODULE-PATH \
         --strip-debug \
         --no-man-pages \
         --no-header-files \
         --compress=2 \
         --output /javaruntime

# Build custom JRE image on top of same base
FROM centos:7

# Insert our custom JRE
ENV JAVA_HOME=/opt/java/openjdk
ENV PATH "${JAVA_HOME}/bin:${PATH}"
COPY --from=jre-build /javaruntime $JAVA_HOME

# Apply other application details
[...]
```

This had a great impact on our completed application image. It went from 414 Mb too 272 Mb without sacrificing on any functionality. If you could add a second tutorial, and hightlight how great these minor changes are, then many people will stop asking for a JRE-17 build.

**Comment by gdams** [comment]
> At first, I was really struggling to get all the available modules, but still saving on space by cutting out all the sdk related components.

@KevinAtSesam did you use `jdeps`? The modules listed in the far right column are those needed for your application.

```
./jdk-17+35/Contents/Home/bin/jdeps HelloWorld.class
HelloWorld.class -> java.base
   <unnamed>                                          -> java.io                                            java.base
   <unnamed>                                          -> java.lang                                          java.base
```

```
./jdk-17+35/Contents/Home/bin/jdeps HelloWorldGUI.class 
HelloWorldGUI.class -> java.base
HelloWorldGUI.class -> java.desktop
   <unnamed>                                          -> java.awt                                           java.desktop
   <unnamed>                                          -> java.lang                                          java.base
   <unnamed>                                          -> javax.swing                                        java.desktop
```

**Comment by KevinAtSesam** [comment]
Nah, I saved myself the fiddling and I just added all modules using `ALL-MODULE-PATH`. I must find a balance between the time it takes to maintain, and the effect it has on the size, and this solution gave me a simple middle ground.
