### ISSUE TITLE
Cannot run jlink in 17-alpine image

### ISSUE THREAD

**Issue by llamahunter** [adoptium/containers#80]
I tried to use jlink to make a 'jre-like' image of 17-alpine. It seems that perhaps a required program is missing from the base image?

Dockerfile:
```
FROM eclipse-temurin:17-jdk-alpine as jre-build

# Create a custom Java runtime
RUN $JAVA_HOME/bin/jlink \
         --add-modules java.base \
         --strip-debug \
         --no-man-pages \
         --no-header-files \
         --compress=2 \
         --output /javaruntime

FROM alpine
ENV JAVA_HOME=/opt/java/openjdk
ENV PATH "${JAVA_HOME}/bin:${PATH}"
COPY --from=jre-build /javaruntime $JAVA_HOME
```

docker build output error
```
 => ERROR [jre-build 2/2] RUN /opt/java/openjdk/bin/jlink          --add-modules java.base          --strip-debug          --no-man-pages          --no-header-files          --com  3.6s
------
 > [jre-build 2/2] RUN /opt/java/openjdk/bin/jlink          --add-modules java.base          --strip-debug          --no-man-pages          --no-header-files          --compress=2          --output /javaruntime:
#7 3.369 Error: java.io.IOException: Cannot run program "objcopy": error=2, No such file or directory
```

It seems that the required `objcopy` is not in the alpine base image?

**Comment by jerboaa** [comment]
Yes, this was introduced with https://bugs.openjdk.java.net/browse/JDK-8219257. One way to work-around this is by using: `--strip-java-debug-attributes` instead of `--strip-debug` in the jlink command. AFAIK, Temurin builds don't contain debuginfo symbols in binaries so stripping native binaries won't be needed.

**Comment by llamahunter** [comment]
Hmm... "There is no risk for adding the new `--strip-native-debug-symbols` plugin."  Seems that there was.
