### ISSUE TITLE
Question: Will there be open9 images again?

### ISSUE THREAD

**Issue by Herr-Sepp** [adoptium/containers#81]
AdoptOpenJDK also provided images with openj9 as an alternative to hotspot. 
Is the deployment through adoptium also planned again?

It would be good to document the status of openj9-images on the Dockerhub page since Adopt links directly to the page.

**Comment by karianna** [comment]
@Herr-Sepp - Can you let me know where that link is?

**Comment by CodingKoopa** [comment]
To answer OP's question, Adoptium will not be providing OpenJ9 images due to licensing reasons related to the terms under which the team was licensed the TCK. See [here](https://github.com/AdoptOpenJDK/openjdk-docker/issues/610#issuecomment-926329200) for a rundown of the situation.

**Comment by Herr-Sepp** [comment]
Thanks CodingKoopa for that link and the research

@karianna [https://hub.docker.com/_/adoptopenjdk](https://hub.docker.com/_/adoptopenjdk)
It is hard to comply with the request "Please adjust your usage accordingly." if you have used openj9-image from this repository. There is no mention of openj9-images on the linked eclipse-temurin page.
A little note about IBM Semeru in the deprecation notice would be helpful there.

**Comment by karianna** [comment]
@gdams - can we add some more context in the deprecation description section? I tried logging in as the adoptopenjdk user but couldn't find a way to update.
