### ISSUE TITLE
Provide Ubuntu 22.04 based image

### ISSUE THREAD

**Issue by itzg** [adoptium/containers#82]
In the [known issues of Docker 3.4.0](https://docs.docker.com/desktop/mac/release-notes/#docker-desktop-340) they report

> On Apple Silicon in native arm64 containers, older versions of libssl in debian:buster, ubuntu:20.04 and centos:8 will segfault when connected to some TLS servers, for example curl https://dl.yarnpkg.com. The bug is fixed in newer versions of libssl in debian:bullseye, ubuntu:21.04 and fedora:35.

I would like to suggest that in addition to the LTS version of each respective distribution (Ubuntu and CentOS, I believe) that an "edge" variant be provided for the newest regular release, such as Ubuntu 21.04. With that said, I am still a huge proponent of the mainline/latest images being based on LTS, so I would not want to see a change to that philosophy.

_Originally posted by @itzg in https://github.com/adoptium/containers/issues/1#issuecomment-927162309_

**Comment by karianna** [comment]
We'll be swapping to 22.04 as a base shortly.
